### ISSUE TITLE
min exposure not working

### ISSUE THREAD

**Issue by NahomTayeGH** [anthonyshook/dfsOptimizer#9]
set_player_min_exp function is not working.

**Comment by anthonyshook** [comment]
In what way?  Can you provide a reproducible example?

**Comment by NahomTayeGH** [comment]
[outputDF.csv](https://github.com/anthonyshook/dfsOptimizer/files/7610749/outputDF.csv)
`#make optimizer
opt <- create_optimizer(site = 'FANDUEL', 
                        sport = 'BASKETBALL', 
                        contest_type = 'CLASSIC')

opt <- add_players_from_df(object = opt, df = outputDf)
#get IDs
min <- get_player_id(opt, 'Mikal Bridges')
min2 <- get_player_id(opt, 'Stephen Curry')
max <- get_player_id(opt,'Dennis Schroder')

opt<-opt%>%set_max_exposure(exp = .5)%>%
  set_max_overlap(overlap = 6)%>%
  set_player_min_exp(id = min2,exp =0.3)%>%
  set_player_max_exp(id = min,exp =0.3)%>%
  set_player_max_exp(id = max,exp =.2)

lineups <- build_lineups(opt, num_lineups = 10)
summary(lineups)`

when I run the code above, from my understanding Stephen Curry and Mikal Bridges should appear in at least 3 lineups however both curry and bridges appear in 0 lineups.

**Comment by anthonyshook** [comment]
Thanks, I was able to reproduce the issue, and I'll look into it!

**Comment by anthonyshook** [comment]
Just pushed an update to master that should fix the issue, so just re-install the package!

The exposures might not be _exactly_ minimum all the time, because of rounding errors, but they will always at least _approximate_ the provided exposure percentage.
